[build]
  command = "npm run build"
  publish = ".next"
  
  # Configure secrets scanning to omit public environment variables
  environment = { SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,SUPABASE_STORAGE_BUCKET" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Function settings
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Headers for caching static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"